# Prometheus — Configuration locale (dev)
# L'app tourne sur l'hôte → host.docker.internal:8081
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'mixx-expresso'
    metrics_path: '/management/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']